<a href="https://colab.research.google.com/github/steciow/Colaborador/blob/main/COVID_Internacional.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PROCESAMIENTO DE BASE DIARIA DE CASOS REGISTRADOS EN EL MUNDO**

Fuente:

https://ourworldindata.org/coronavirus-data

## **Importar librerías**

In [ ]:
# importamos de librerías que se utilizarán para trabajar las tablas y le otorgamos un alias
import pandas as pd
import numpy as np
from google.colab import files
#import matplotlib.pyplot as plt
#import plotly.express as px

In [ ]:
#para ver mejor el contenido de las tablas, indico el máximo de filas a visualizar en 400...
pd.set_option('display.max_rows',800)

## **Levantar bases**

###**Base de datos internacional**

In [ ]:
#levantar desde enlace web
url='https://covid.ourworldindata.org/data/owid-covid-data.csv'
dfint= pd.read_csv(url)

###**Base de datos de vacunación**

In [ ]:
#levantar base sobre vacunas desde enlace web en github de owid
url='https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv'
dfintvacc=pd.read_csv(url)

## **Explorando la base**

In [ ]:
#primera exploración de la base: tamaño (cantidad de filas, cantidad de columnas)
#tomar nota del total de registros que eso sirve para controlar el resultado de las tablas
dfint.shape

(80322, 59)

In [ ]:
#primera exploración de la base: lista de columnas
dfint.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80322 entries, 0 to 80321
Data columns (total 59 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   iso_code                               80322 non-null  object
 1   continent                              76409 non-null  object
 2   location                               80322 non-null  object
 3   date                                   80322 non-null  object
 4   total_cases                            78694 non-null  float64
 5   new_cases                              78692 non-null  float64
 6   new_cases_smoothed                     77691 non-null  float64
 7   total_deaths                           69218 non-null  float64
 8   new_deaths                             69376 non-null  float64
 9   new_deaths_smoothed                    77691 non-null  float64
 10  total_cases_per_million                78267 non-null  float64
 11  new_cases_per_million                  78265 non-null  float64
 12  new_cases_smoothed_per_million         77269 non-null  float64
 13  total_deaths_per_million               68804 non-null  float64
 14  new_deaths_per_million                 68962 non-null  float64
 15  new_deaths_smoothed_per_million        77269 non-null  float64
 16  reproduction_rate                      64756 non-null  float64
 17  icu_patients                           8456 non-null   float64
 18  icu_patients_per_million               8456 non-null   float64
 19  hosp_patients                          10127 non-null  float64
 20  hosp_patients_per_million              10127 non-null  float64
 21  weekly_icu_admissions                  743 non-null    float64
 22  weekly_icu_admissions_per_million      743 non-null    float64
 23  weekly_hosp_admissions                 1240 non-null   float64
 24  weekly_hosp_admissions_per_million     1240 non-null   float64
 25  new_tests                              36931 non-null  float64
 26  total_tests                            36661 non-null  float64
 27  total_tests_per_thousand               36661 non-null  float64
 28  new_tests_per_thousand                 36931 non-null  float64
 29  new_tests_smoothed                     42246 non-null  float64
 30  new_tests_smoothed_per_thousand        42246 non-null  float64
 31  positive_rate                          40925 non-null  float64
 32  tests_per_case                         40309 non-null  float64
 33  tests_units                            43640 non-null  object
 34  total_vaccinations                     6820 non-null   float64
 35  people_vaccinated                      6192 non-null   float64
 36  people_fully_vaccinated                4391 non-null   float64
 37  new_vaccinations                       5777 non-null   float64
 38  new_vaccinations_smoothed              10802 non-null  float64
 39  total_vaccinations_per_hundred         6820 non-null   float64
 40  people_vaccinated_per_hundred          6192 non-null   float64
 41  people_fully_vaccinated_per_hundred    4391 non-null   float64
 42  new_vaccinations_smoothed_per_million  10802 non-null  float64
 43  stringency_index                       68455 non-null  float64
 44  population                             79824 non-null  float64
 45  population_density                     74865 non-null  float64
 46  median_age                             72607 non-null  float64
 47  aged_65_older                          71775 non-null  float64
 48  aged_70_older                          72199 non-null  float64
 49  gdp_per_capita                         72906 non-null  float64
 50  extreme_poverty                        49715 non-null  float64
 51  cardiovasc_death_rate                  73497 non-null  float64
 52  diabetes_prevalence                    74480 non-null  float64
 53  female_smokers                         57688 non-null  float64
 54  male_smokers                           56836 non-null  float64
 55  handwashing_facilities                 36917 non-null  float64
 56  hospital_beds_per_thousand             67179 non-null  float64
 57  life_expectancy                        76245 non-null  float64
 58  human_development_index                73439 non-null  float64
dtypes: float64(54), object(5)
memory usage: 36.2+ MB

In [ ]:
#para ver el encabezado (y primeras 5 filas)
dfint.head(5)

  iso_code continent  ... life_expectancy human_development_index
0      AFG      Asia  ...           64.83                   0.511
1      AFG      Asia  ...           64.83                   0.511
2      AFG      Asia  ...           64.83                   0.511
3      AFG      Asia  ...           64.83                   0.511
4      AFG      Asia  ...           64.83                   0.511

[5 rows x 59 columns]

In [ ]:
dfintvacc.info

<bound method DataFrame.info of           location  ... daily_vaccinations_per_million
0      Afghanistan  ...                            NaN
1      Afghanistan  ...                           35.0
2      Afghanistan  ...                           35.0
3      Afghanistan  ...                           35.0
4      Afghanistan  ...                           35.0
...            ...  ...                            ...
11459     Zimbabwe  ...                          572.0
11460     Zimbabwe  ...                          574.0
11461     Zimbabwe  ...                          614.0
11462     Zimbabwe  ...                          738.0
11463     Zimbabwe  ...                          841.0

[11464 rows x 12 columns]>

In [ ]:
dfintvacc.head(5)

      location  ... daily_vaccinations_per_million
0  Afghanistan  ...                            NaN
1  Afghanistan  ...                           35.0
2  Afghanistan  ...                           35.0
3  Afghanistan  ...                           35.0
4  Afghanistan  ...                           35.0

[5 rows x 12 columns]

## **Procesos**

###**Formato**

In [ ]:
#para pasar del inglés al castellano las etiquetas de los países países
dfint['location'].replace({'United States':'EEUU', 
                    'World':'Mundo',
                    'Spain':'España', 
                    'United Kingdom':'Reino Unido',
                    'Italy':'Italia', 
                    'Brazil':'Brasil'}, inplace=True)

In [ ]:
dfintvacc['location'].replace({'United States':'EEUU', 
                    'World':'Mundo',
                    'Spain':'España', 
                    'United Kingdom':'Reino Unido',
                    'Italy':'Italia', 
                    'Brazil':'Brasil'}, inplace=True)

### **Elaboración de tabla resumen**

In [ ]:
#resumen tabla internacional seleccionando algunos países (EEUU, Italia, Brasil, España, Argentina, Chile, Peru y "El Mundo")
dfintfiltrada=dfint.loc[dfint['location'].isin(['Mundo','EEUU','Brasil','Argentina','Italia','España','Chile','Uruguay','Paraguay','India','Reino Unido','Peru'])] #esto es para seleccionar únicamente algunos países y el mundo

In [ ]:
dfintvaccfiltrada=dfintvacc.loc[dfintvacc['location'].isin(['Mundo','EEUU','Brasil','Argentina','Italia','España','Chile','Uruguay','Paraguay','India','Reino Unido','Peru'])] #esto es para seleccionar únicamente algunos países y el mundo

###**Unión**

In [ ]:
#unión de datos de contagios y de vacunas por país
dffinal = pd.concat([dfintfiltrada,dfintvaccfiltrada],sort=False) #por defecto es un "outer join"
dffinal

       iso_code  ... daily_vaccinations_per_million
2873        ARG  ...                            NaN
2874        ARG  ...                            NaN
2875        ARG  ...                            NaN
2876        ARG  ...                            NaN
2877        ARG  ...                            NaN
...         ...  ...                            ...
11410  OWID_WRL  ...                         2087.0
11411  OWID_WRL  ...                         2053.0
11412  OWID_WRL  ...                         2110.0
11413  OWID_WRL  ...                         2087.0
11414  OWID_WRL  ...                         2087.0

[6212 rows x 62 columns]

## **Guardado / descarga**

In [ ]:
#guardado de base con datos internacionales
dffinal.to_csv('/content/drive/MyDrive/Proyectos/COVID/tablainternacional.csv',header=True,index=False,sep=",",encoding='utf-8-sig')

In [ ]:
#si se descarga en carpeta 'descargas'
#dffinal.to_csv('tablainternacional.csv')
#files.download('tablainternacional.csv')